name: annette
favicon: null
layout_spectrum: 0.8328548923600465
typography_spectrum: 0.5323827888350934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3964351878967136
  lightness: 0.9921356472186744
  saturation: 0.2374191207345575
  rhythmicContrast: 0.4969516615383327
purpose: []
